spring:
  application:
    name: store

app:
  page-size: 10

stripe:
  api-url: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP

payment-gateway: stripe

mail:
  host: http://smtp.gmail.com
  port: 5761
